package com.example.util

object AppStrings {

    fun get(key: String, lang: String): String {
        val l = lang.lowercase()
        return when (key) {
            // Navigation
            "nav_garden", "tab_garden" -> when (l) {
                "bn" -> "গার্ডেন"
                "es" -> "Jardín"
                "hi" -> "गार्डन"
                "ar" -> "الحديقة"
                "fr" -> "Jardin"
                "de" -> "Garten"
                "zh" -> "花园"
                "pt" -> "Jardim"
                "ru" -> "Сад"
                "ja" -> "庭園"
                "ko" -> "정원"
                "id" -> "Taman"
                "tr" -> "Bahçe"
                "ur" -> "باغ"
                else -> "Garden"
            }
            "nav_stats", "tab_stats" -> when (l) {
                "bn" -> "পরিসংখ্যান"
                "es" -> "Estadísticas"
                "hi" -> "आंकड़े"
                "ar" -> "الإحصائيات"
                "fr" -> "Statistiques"
                "de" -> "Statistiken"
                "zh" -> "统计"
                "pt" -> "Estatísticas"
                "ru" -> "Статистика"
                "ja" -> "統計"
                "ko" -> "통계"
                "id" -> "Statistik"
                "tr" -> "İstatistikler"
                "ur" -> "اعداد و شمار"
                else -> "Stats"
            }
            "nav_habits", "tab_habits" -> when (l) {
                "bn" -> "অভ্যাসসমূহ"
                "es" -> "Hábitos"
                "hi" -> "आदते"
                "ar" -> "العادات"
                "fr" -> "Habitudes"
                "de" -> "Gewohnheiten"
                "zh" -> "习惯"
                "pt" -> "Hábitos"
                "ru" -> "Привычки"
                "ja" -> "習慣"
                "ko" -> "습관"
                "id" -> "Kebiasaan"
                "tr" -> "Alışkanlıklar"
                "ur" -> "عادات"
                else -> "Habits"
            }
            "nav_profile", "tab_profile" -> when (l) {
                "bn" -> "প্রোফাইল"
                "es" -> "Perfil"
                "hi" -> "प्रोफ़ाइल"
                "ar" -> "الملف"
                "fr" -> "Profil"
                "de" -> "Profil"
                "zh" -> "个人资料"
                "pt" -> "Perfil"
                "ru" -> "Профиль"
                "ja" -> "プロフィール"
                "ko" -> "프로필"
                "id" -> "Profil"
                "tr" -> "Profil"
                "ur" -> "پروفائل"
                else -> "Profile"
            }

            // Home Screen
            "default_habit_title" -> when (l) {
                "bn" -> "অভ্যাস ট্র্যাকার"
                "es" -> "Rastreador de Hábitos"
                "hi" -> "आदत ट्रैकर"
                "ar" -> "متتبع العادات"
                "fr" -> "Suivi d'habitudes"
                "de" -> "Gewohnheitstracker"
                "zh" -> "习惯追踪器"
                "pt" -> "Rastreador de Hábitos"
                "ru" -> "Трекер привычек"
                "ja" -> "習慣トラッカー"
                "ko" -> "습관 추적기"
                "id" -> "Pelacak Kebiasaan"
                "tr" -> "Alışkanlık Takipçisi"
                "ur" -> "عادت ٹریکر"
                else -> "Habit Tracker"
            }
            "default_habit_sub" -> when (l) {
                "bn" -> "অভ্যাসমুক্ত জীবনের নতুন শুরু"
                "es" -> "Un nuevo comienzo hacia una vida libre de hábitos"
                "hi" -> "आदत-मुक्त जीवन की एक नई शुरुआत"
                "ar" -> "بداية جديدة نحو حياة خالية من العادات"
                "fr" -> "Un nouveau départ vers une vie libre"
                "de" -> "Ein Neuanfang für ein gewohnheitsfreies Leben"
                "zh" -> "开启无习惯负担的新生活"
                "pt" -> "Um novo começo para uma vida livre"
                "ru" -> "Новое начало к жизни без привычек"
                "ja" -> "習慣から解放された新しい人生の始まり"
                "ko" -> "습관에서 벗어난 삶을 향한 새로운 시작"
                "id" -> "Awal baru menuju hidup bebas kebiasaan"
                "tr" -> "Alışkanlıksız bir hayata yeni bir başlangıç"
                "ur" -> "عادت سے پاک زندگی کا نیا آغاز"
                else -> "A new start towards a habit-free life"
            }
            "add_new_habit_btn" -> when (l) {
                "bn" -> "+ নতুন অভ্যাস যোগ করুন"
                "es" -> "+ Añadir nuevo hábito"
                "hi" -> "+ नई आदत जोड़ें"
                "ar" -> "+ إضافة عادة جديدة"
                "fr" -> "+ Ajouter une habitude"
                "de" -> "+ Neue Gewohnheit hinzufügen"
                "zh" -> "+ 添加新习惯"
                "pt" -> "+ Adicionar novo hábito"
                "ru" -> "+ Добавить привычку"
                "ja" -> "+ 新しい習慣を追加"
                "ko" -> "+ 새 습관 추가"
                "id" -> "+ Tambah Kebiasaan Baru"
                "tr" -> "+ Yeni Alışkanlık Ekle"
                "ur" -> "+ نئی عادت شامل کریں"
                else -> "+ Add New Habit"
            }
            "stage_level" -> when (l) {
                "bn" -> "পর্যায়"
                "es" -> "Nivel"
                "hi" -> "चरण"
                "ar" -> "المرحلة"
                "fr" -> "Niveau"
                "de" -> "Stufe"
                "zh" -> "阶段"
                "pt" -> "Nível"
                "ru" -> "Этап"
                "ja" -> "ステージ"
                "ko" -> "단계"
                "id" -> "Tahap"
                "tr" -> "Aşama"
                "ur" -> "مرحلہ"
                else -> "Stage"
            }
            "master_achieved" -> when (l) {
                "bn" -> "মহীরুহ অর্জিত!"
                "es" -> "¡Gran Árbol Alcanzado!"
                "hi" -> "महान वृक्ष प्राप्त हुआ!"
                "ar" -> "تم تحقيق الشجرة العظيمة!"
                "fr" -> "Grand Arbre Atteint!"
                "de" -> "Meisterbaum Erreicht!"
                "zh" -> "已长成参天大树！"
                "pt" -> "Grande Árvore Alcançada!"
                "ru" -> "Величественное дерево выращено!"
                "ja" -> "大樹達成！"
                "ko" -> "거목 달성!"
                "id" -> "Pohon Besar Tercapai!"
                "tr" -> "Büyük Ağaç Başarıldı!"
                "ur" -> "عظیم درخت حاصل ہو گیا!"
                else -> "Master Tree Achieved!"
            }
            "next_stage" -> when (l) {
                "bn" -> "পরবর্তী স্তর"
                "es" -> "Siguiente etapa"
                "hi" -> "अगला चरण"
                "ar" -> "المرحلة التالية"
                "fr" -> "Prochaine étape"
                "de" -> "Nächste Stufe"
                "zh" -> "下一阶段"
                "pt" -> "Próxima etapa"
                "ru" -> "Следующий этап"
                "ja" -> "次のステージ"
                "ko" -> "다음 단계"
                "id" -> "Tahap Berikutnya"
                "tr" -> "Sonraki Aşama"
                "ur" -> "اگلا مرحلہ"
                else -> "Next Stage"
            }
            "max_growth_achieved" -> when (l) {
                "bn" -> "সর্বোচ্চ বিকাশ অর্জিত"
                "es" -> "Máximo Crecimiento Alcanzado"
                "hi" -> "अधिकतम विकास प्राप्त हुआ"
                "ar" -> "تم الوصول إلى أقصى نمو"
                "fr" -> "Croissance maximale atteinte"
                "de" -> "Maximales Wachstum erreicht"
                "zh" -> "已达到最大生长"
                "pt" -> "Crescimento máximo alcançado"
                "ru" -> "Достигнут максимальный рост"
                "ja" -> "最大成長達成"
                "ko" -> "최대 성장 달성"
                "id" -> "Pertumbuhan Maksimal Tercapai"
                "tr" -> "Maksimum Büyüme Başarıldı"
                "ur" -> "زیادہ سے زیادہ نمو حاصل ہو گئی"
                else -> "Maximum Growth Achieved"
            }
            "goal_days" -> when (l) {
                "bn" -> "লক্ষ্য"
                "es" -> "Meta"
                "hi" -> "लक्ष्य"
                "ar" -> "الهدف"
                "fr" -> "Objectif"
                "de" -> "Ziel"
                "zh" -> "目标"
                "pt" -> "Meta"
                "ru" -> "Цель"
                "ja" -> "目標"
                "ko" -> "목표"
                "id" -> "Target"
                "tr" -> "Hedef"
                "ur" -> "ہدفی دن"
                else -> "Goal"
            }
            "congrats_30_days" -> when (l) {
                "bn" -> "অভিনন্দন! আপনি ৩০+ দিনের মাইলফলক ছুঁয়েছেন!"
                "es" -> "¡Felicidades! ¡Has alcanzado el hito de más de 30 días!"
                "hi" -> "बधाई हो! आपने 30+ दिनों का मील का पत्थर पार कर लिया!"
                "ar" -> "تهانينا! لقد وصلت إلى إنجاز 30+ يومًا!"
                "fr" -> "Félicitations! Vous avez atteint l'étape de 30+ jours!"
                "de" -> "Glückwunsch! Du hast den 30+ Tage Meilenstein erreicht!"
                "zh" -> "恭喜！您已突破 30+ 天里程碑！"
                "pt" -> "Parabéns! Você atingiu o marco de 30+ dias!"
                "ru" -> "Поздравляем! Вы достигли рубежа в 30+ дней!"
                "ja" -> "おめでとうございます！30日以上のマイルストーンを達成しました！"
                "ko" -> "축하합니다! 30일 이상의 이정표를 달성했습니다!"
                "id" -> "Selamat! Anda telah mencapai pencapaian 30+ hari!"
                "tr" -> "Tebrikler! 30+ günlük dönüm noktasına ulaştınız!"
                "ur" -> "مبارک ہو! آپ نے 30+ دن کا سنگ میل حاصل کر لیا!"
                else -> "Congratulations! You reached the 30+ day milestone!"
            }
            "seed_tree_theme_btn" -> when (l) {
                "bn" -> "🎨 বীজ ও গাছের থিম: %s (ট্যাপ করে পরিবর্তন)"
                "es" -> "🎨 Tema de Semilla y Árbol: %s (Toca para cambiar)"
                "hi" -> "🎨 बीज और वृक्ष थीम: %s (बदलने के लिए टैप करें)"
                "ar" -> "🎨 مظهر البذرة والشجرة: %s (انقر للتغيير)"
                "fr" -> "🎨 Thème Graine & Arbre: %s (Appuyer pour changer)"
                "de" -> "🎨 Samen- & Baum-Design: %s (Tippen zum Ändern)"
                "zh" -> "🎨 种子与树木主题：%s（点击切换）"
                "pt" -> "🎨 Tema de Semente e Árvore: %s (Toque para mudar)"
                "ru" -> "🎨 Тема семени и дерева: %s (Нажмите для смены)"
                "ja" -> "🎨 種とツリーのテーマ: %s (タップして変更)"
                "ko" -> "🎨 씨앗 & 나무 테마: %s (터치하여 변경)"
                "id" -> "🎨 Tema Benih & Pohon: %s (Ketuk untuk mengubah)"
                "tr" -> "🎨 Tohum ve Ağaç Teması: %s (Değiştirmek için dokunun)"
                "ur" -> "🎨 بیج اور درخت کا تھیم: %s (تبدیل کرنے کے لیے ٹیپ کریں)"
                else -> "🎨 Seed & Tree Theme: %s (Tap to change)"
            }
            "timer_title" -> when (l) {
                "bn" -> "অভ্যাসমুক্ত সময়"
                "es" -> "Tiempo Libre del Hábito"
                "hi" -> "आदत-मुक्त समय"
                "ar" -> "الوقت الخالي من العادة"
                "fr" -> "Temps Libre d'Habitude"
                "de" -> "Gewohnheitsfreie Zeit"
                "zh" -> "远离习惯的时间"
                "pt" -> "Tempo Livre do Hábito"
                "ru" -> "Время без привычки"
                "ja" -> "習慣から解放された時間"
                "ko" -> "습관에서 벗어난 시간"
                "id" -> "Waktu Bebas Dari Kebiasaan"
                "tr" -> "Alışkanlıktan Uzak Süre"
                "ur" -> "عادت سے پاک وقت"
                else -> "Time Free From Habit"
            }
            "label_days" -> when (l) {
                "bn" -> "দিন"
                "es" -> "Días"
                "hi" -> "दिन"
                "ar" -> "أيام"
                "fr" -> "Jours"
                "de" -> "Tage"
                "zh" -> "天"
                "pt" -> "Dias"
                "ru" -> "Дни"
                "ja" -> "日"
                "ko" -> "일"
                "id" -> "Hari"
                "tr" -> "Gün"
                "ur" -> "دن"
                else -> "Days"
            }
            "label_hours" -> when (l) {
                "bn" -> "ঘণ্টা"
                "es" -> "Horas"
                "hi" -> "घंटे"
                "ar" -> "ساعات"
                "fr" -> "Heures"
                "de" -> "Stunden"
                "zh" -> "小时"
                "pt" -> "Horas"
                "ru" -> "Часы"
                "ja" -> "時間"
                "ko" -> "시간"
                "id" -> "Jam"
                "tr" -> "Saat"
                "ur" -> "گھنٹے"
                else -> "Hours"
            }
            "label_mins" -> when (l) {
                "bn" -> "মিনিট"
                "es" -> "Mins"
                "hi" -> "मिनट"
                "ar" -> "دقائق"
                "fr" -> "Mins"
                "de" -> "Min"
                "zh" -> "分钟"
                "pt" -> "Mins"
                "ru" -> "Мин"
                "ja" -> "分"
                "ko" -> "분"
                "id" -> "Menit"
                "tr" -> "Dak"
                "ur" -> "منٹ"
                else -> "Mins"
            }
            "label_secs" -> when (l) {
                "bn" -> "সেকেন্ড"
                "es" -> "Segs"
                "hi" -> "सेकंड"
                "ar" -> "ثواني"
                "fr" -> "Secs"
                "de" -> "Sek"
                "zh" -> "秒"
                "pt" -> "Segs"
                "ru" -> "Сек"
                "ja" -> "秒"
                "ko" -> "초"
                "id" -> "Detik"
                "tr" -> "San"
                "ur" -> "سیکنڈ"
                else -> "Secs"
            }
            "i_relapsed_btn" -> when (l) {
                "bn" -> "আমি ভুল করে ফেলেছি (Relapse)"
                "es" -> "Tuve una recaída (Reiniciar)"
                "hi" -> "मुझसे गलती हो गई (रिलेप्स)"
                "ar" -> "لقد انزلقت (إعادة ضبط)"
                "fr" -> "J'ai rechuté (Réinitialiser)"
                "de" -> "Ich hatte einen Rückfall (Reset)"
                "zh" -> "我复发了（重置计时器）"
                "pt" -> "Tive uma recaída (Reiniciar)"
                "ru" -> "Я сорвался (Сбросить таймер)"
                "ja" -> "リバウンドしました (リセット)"
                "ko" -> "재발했습니다 (타이머 리셋)"
                "id" -> "Saya Kambuh (Reset Timer)"
                "tr" -> "Tekrarlandım (Zamanlayıcıyı Sıfırla)"
                "ur" -> "مجھ سے غلطی ہو گئی (ری سیٹ کریں)"
                else -> "I Relapsed (Reset Timer)"
            }
            "daily_thought" -> when (l) {
                "bn" -> "আজকের প্রেরণা"
                "es" -> "Pensamiento Diario"
                "hi" -> "आज का विचार"
                "ar" -> "حكمة اليوم"
                "fr" -> "Pensée du jour"
                "de" -> "Tagesgedanke"
                "zh" -> "每日一言"
                "pt" -> "Pensamento do Dia"
                "ru" -> "Мысль дня"
                "ja" -> "今日の格言"
                "ko" -> "오늘의 명언"
                "id" -> "Inspirasi Hari Ini"
                "tr" -> "Günün Düşüncesi"
                "ur" -> "آج کی بات"
                else -> "Daily Thought"
            }
            "milestone_header" -> when (l) {
                "bn" -> "🌱 গাছ বৃদ্ধির মাইলফলক পর্যায়সমূহ"
                "es" -> "🌱 Hitos del Crecimiento del Árbol"
                "hi" -> "🌱 वृक्ष विकास के मील के पत्थर"
                "ar" -> "🌱 مراحل نمو الشجرة"
                "fr" -> "🌱 Étapes de croissance de l'arbre"
                "de" -> "🌱 Meilensteine des Baumwachstums"
                "zh" -> "🌱 树木生长里程碑"
                "pt" -> "🌱 Marcos de Crescimento da Árbol"
                "ru" -> "🌱 Этапы роста дерева"
                "ja" -> "🌱 ツリー成長のマイルストーン"
                "ko" -> "🌱 나무 성장 이정표"
                "id" -> "🌱 Tahapan Pertumbuhan Pohon"
                "tr" -> "🌱 Ağaç Büyüme Dönüm Noktaları"
                "ur" -> "🌱 درخت کی نمو کے سنگ میل"
                else -> "🌱 Tree Growth Milestones"
            }

            // Milestone items
            "m_seed_day" -> when (l) {
                "bn" -> "প্রথম দিন (০-২ দিন)"
                "es" -> "Día 0-2"
                "hi" -> "दिन 0-2"
                "ar" -> "يوم 0-2"
                "fr" -> "Jour 0-2"
                "de" -> "Tag 0-2"
                "zh" -> "第 0-2 天"
                "pt" -> "Dia 0-2"
                "ru" -> "День 0-2"
                "ja" -> "0〜2日目"
                "ko" -> "0-2일차"
                "id" -> "Hari 0-2"
                "tr" -> "Gün 0-2"
                "ur" -> "دن 0-2"
                else -> "Day 0-2"
            }
            "m_seed_title" -> when (l) {
                "bn" -> "বীজ (Seed)"
                "es" -> "Semilla"
                "hi" -> "बीज (Seed)"
                "ar" -> "بذرة"
                "fr" -> "Graine"
                "de" -> "Samen"
                "zh" -> "种子"
                "pt" -> "Semente"
                "ru" -> "Семя"
                "ja" -> "種 (Seed)"
                "ko" -> "씨앗 (Seed)"
                "id" -> "Benih (Seed)"
                "tr" -> "Tohum (Seed)"
                "ur" -> "بیج"
                else -> "Seed"
            }
            "m_seed_desc" -> when (l) {
                "bn" -> "নতুন সংকল্পের বীজ মাটিতে রোপণ করা হলো।"
                "es" -> "Plantando la semilla de un nuevo compromiso."
                "hi" -> "एक नए संकल्प का बीज बोया गया।"
                "ar" -> "زراعة بذرة التزام جديد."
                "fr" -> "Plantation de la graine d'un nouvel engagement."
                "de" -> "Pflanzen des Samens einer neuen Verpflichtung."
                "zh" -> "在土壤中播下新决心的种子。"
                "pt" -> "Plantando a semente de um novo compromisso."
                "ru" -> "Посадка семени нового обязательства."
                "ja" -> "新しい決意の種を植えました。"
                "ko" -> "새로운 다짐의 씨앗을 심었습니다."
                "id" -> "Menanam benih komitmen baru."
                "tr" -> "Yeni bir taahhüdün tohumu ekildi."
                "ur" -> "نئے عزم کا بیج بویا گیا۔"
                else -> "Planting the seed of a new commitment."
            }

            "m_sprout_day" -> when (l) {
                "bn" -> "৩ দিন পর"
                "es" -> "Día 3+"
                "hi" -> "3 दिन बाद"
                "ar" -> "بعد 3 أيام"
                "fr" -> "Jour 3+"
                "de" -> "Tag 3+"
                "zh" -> "3 天后"
                "pt" -> "Dia 3+"
                "ru" -> "3+ дней"
                "ja" -> "3日後"
                "ko" -> "3일 후"
                "id" -> "3 Hari+"
                "tr" -> "3. Gün+"
                "ur" -> "3 دن بعد"
                else -> "Day 3+"
            }
            "m_sprout_title" -> when (l) {
                "bn" -> "ছোট অঙ্কুর (Sprout)"
                "es" -> "Brote Verde"
                "hi" -> "अंकुर (Sprout)"
                "ar" -> "برعم"
                "fr" -> "Pousse"
                "de" -> "Spross"
                "zh" -> "幼芽"
                "pt" -> "Brotinho"
                "ru" -> "Росток"
                "ja" -> "新芽 (Sprout)"
                "ko" -> "새싹 (Sprout)"
                "id" -> "Tunas (Sprout)"
                "tr" -> "Filiz (Sprout)"
                "ur" -> "ننہا پودا"
                else -> "Sprout"
            }
            "m_sprout_desc" -> when (l) {
                "bn" -> "৩ দিনের আত্মনিয়ন্ত্রণে বের হলো ছোট সবুজ অঙ্কুর।"
                "es" -> "3 días de autocontrol dan vida a un brote verde."
                "hi" -> "3 दिनों के आत्म-नियंत्रण से एक हरा अंकुर निकला।"
                "ar" -> "3 أيام من ضبط النفس تخرج برعماً أخضر."
                "fr" -> "3 jours d'autocontrôle font émerger une jeune pousse."
                "de" -> "3 Tage Selbstbeherrschung bringen einen grünen Spross hervor."
                "zh" -> "3天的自律让嫩绿的幼芽破土而出。"
                "pt" -> "3 dias de autocontrole revelam um broto verde."
                "ru" -> "3 дня самоконтроля дают жизнь зеленому ростку."
                "ja" -> "3日間の self-control で緑の新芽が顔を出しました。"
                "ko" -> "3일간의 절제로 푸른 새싹이 돋아났습니다."
                "id" -> "3 hari kontrol diri memunculkan tunas hijau."
                "tr" -> "3 günlük özdenetim yeşil bir filiz çıkardı."
                "ur" -> "3 دن کے ضبط نفس سے ایک ننہا سبز پودا نکل آیا۔"
                else -> "3 days of self-control brings out a green sprout."
            }

            "m_sapling_day" -> when (l) {
                "bn" -> "৭ দিন পর"
                "es" -> "Día 7+"
                "hi" -> "7 दिन बाद"
                "ar" -> "بعد 7 أيام"
                "fr" -> "Jour 7+"
                "de" -> "Tag 7+"
                "zh" -> "7 天后"
                "pt" -> "Dia 7+"
                "ru" -> "7+ дней"
                "ja" -> "7日後"
                "ko" -> "7일 후"
                "id" -> "7 Hari+"
                "tr" -> "7. Gün+"
                "ur" -> "7 دن بعد"
                else -> "Day 7+"
            }
            "m_sapling_title" -> when (l) {
                "bn" -> "চারা গাছ (Sapling)"
                "es" -> "Plántula Fuerte"
                "hi" -> "पौधा (Sapling)"
                "ar" -> "شتلة"
                "fr" -> "Jeune Arbre"
                "de" -> "Setzling"
                "zh" -> "树苗"
                "pt" -> "Muda"
                "ru" -> "Саженец"
                "ja" -> "若木 (Sapling)"
                "ko" -> "묘목 (Sapling)"
                "id" -> "Pohon Muda (Sapling)"
                "tr" -> "Fidan (Sapling)"
                "ur" -> "چوٹا درخت"
                else -> "Sapling"
            }
            "m_sapling_desc" -> when (l) {
                "bn" -> "এক সপ্তাহের সাফল্যে চারা গাছটি শক্ত ও সোজা হলো।"
                "es" -> "Una semana de éxito convierte el brote en una plántula fuerte."
                "hi" -> "एक सप्ताह की सफलता ने पौधे को मजबूत बनाया।"
                "ar" -> "أسبوع من النجاح يحولها إلى شتلة قوية."
                "fr" -> "Une semaine de succès le transforme en un jeune arbre fort."
                "de" -> "Eine Woche Erfolg lässt einen starken Setzling heranwachsen."
                "zh" -> "一周的坚持让树苗变得健壮直立。"
                "pt" -> "Uma semana de sucesso transforma-a em uma muda forte."
                "ru" -> "Неделя успеха превращает росток в крепкий саженец."
                "ja" -> "1週間の成功で、しっかりと直立する若木に成長しました。"
                "ko" -> "일주일간의 성공으로 튼튼한 묘목이 되었습니다."
                "id" -> "Satu minggu keberhasilan menjadikannya pohon muda yang kuat."
                "tr" -> "Bir haftalık başarı onu güçlü bir fidana dönüştürdü."
                "ur" -> "ایک ہفتے کی کامیابی نے پودے کو مضبوط بنا دیا۔"
                else -> "One week of success turns it into a strong sapling."
            }

            "m_tree_day" -> when (l) {
                "bn" -> "৩০ দিন পর"
                "es" -> "Día 30+"
                "hi" -> "30 दिन बाद"
                "ar" -> "بعد 30 يومًا"
                "fr" -> "Jour 30+"
                "de" -> "Tag 30+"
                "zh" -> "30 天后"
                "pt" -> "Dia 30+"
                "ru" -> "30+ дней"
                "ja" -> "30日後"
                "ko" -> "30일 후"
                "id" -> "30 Hari+"
                "tr" -> "30. Gün+"
                "ur" -> "30 دن بعد"
                else -> "Day 30+"
            }
            "m_tree_title" -> when (l) {
                "bn" -> "বড় গাছ (Big Tree)"
                "es" -> "Gran Árbol"
                "hi" -> "बड़ा वृक्ष (Big Tree)"
                "ar" -> "شجرة كبيرة"
                "fr" -> "Grand Arbre"
                "de" -> "Großer Baum"
                "zh" -> "参天大树"
                "pt" -> "Grande Árvore"
                "ru" -> "Большое Дерево"
                "ja" -> "大樹 (Big Tree)"
                "ko" -> "거목 (Big Tree)"
                "id" -> "Pohon Rindang (Big Tree)"
                "tr" -> "Büyük Ağaç (Big Tree)"
                "ur" -> "بڑا درخت"
                else -> "Big Tree"
            }
            "m_tree_desc" -> when (l) {
                "bn" -> "এক মাসের সুদৃঢ় চেষ্টায় গড়ে উঠলো এক বিশাল মহীরুহ।"
                "es" -> "Un mes de dedicación hace crecer un árbol majestuoso."
                "hi" -> "एक महीने के दृढ़ प्रयास से एक विशाल वृक्ष बना।"
                "ar" -> "شهر من التفاني ينشئ شجرة مهيبة."
                "fr" -> "Un mois de dévouement fait pousser un arbre majestueux."
                "de" -> "Ein Monat Hingabe lässt einen majestätischen Baum entstehen."
                "zh" -> "整整一月的持之以恒，长成了繁茂的参天大树。"
                "pt" -> "Um mês de dedicação cultiva uma árvore majestosa."
                "ru" -> "Месяц упорства превращает намерение в величественное дерево."
                "ja" -> "1ヶ月の献身的な努力で、立派な大樹へと成長しました。"
                "ko" -> "한 달간의 확고한 노력으로 거대한 나무가 만들어졌습니다."
                "id" -> "Satu bulan dedikasi menumbuhkan pohon yang megah."
                "tr" -> "Bir aylık kararlılık görkemli bir ağaç yetiştirdi."
                "ur" -> "ایک مہینے کی مسلسل کوشش سے ایک عظیم درخت بن گیا۔"
                else -> "One month of dedication grows a majestic tree."
            }

            // Relapse Dialog
            "relapse_dialog_title" -> when (l) {
                "bn" -> "রিলেপস বা ভুল রেকর্ড করুন"
                "es" -> "Registrar Recaída"
                "hi" -> "रिलेप्स या गलती दर्ज करें"
                "ar" -> "تسجيل الانزلاق أو الخطأ"
                "fr" -> "Enregistrer une rechute"
                "de" -> "Rückfall verzeichnen"
                "zh" -> "记录复发"
                "pt" -> "Registrar Recaída"
                "ru" -> "Зафиксировать срыв"
                "ja" -> "リバウンドを記録"
                "ko" -> "재발 기록하기"
                "id" -> "Catat Kekambuhan"
                "tr" -> "Tekrarlamayı Kaydet"
                "ur" -> "غلطی ریکارڈ کریں"
                else -> "Record Relapse"
            }
            "relapse_dialog_sub" -> when (l) {
                "bn" -> "মন খারাপ করবেন না। ভুল থেকে শিক্ষা নিয়েই মানুষ সামনে এগিয়ে যায়। টাইমার আবার বীজ থেকে শুরু হবে।"
                "es" -> "No te desanimes. Aprender de los errores da fuerza. El temporizador volverá a empezar desde la semilla."
                "hi" -> "हताश न हों। गलतियों से सीखकर ही इंसान आगे बढ़ता है। टाइमर फिर से बीज से शुरू होगा।"
                "ar" -> "لا تحزن. نتعلم من الأخطاء لننمو ونستمر. سيعاد تشغيل المؤقت من البذرة."
                "fr" -> "Ne soyez pas découragé. On apprend de ses erreurs. Le minuteur redémarrera depuis la graine."
                "de" -> "Lass dich nicht entmutigen. Aus Fehlern lernt man. Der Timer startet wieder beim Samen."
                "zh" -> "不要灰心。从失败中吸取教训方能更加强大。计时器将重新从种子阶段开始。"
                "pt" -> "Não desanime. Aprender com os erros fortalece. O temporizador recomeçará da semente."
                "ru" -> "Не падайте духом! Ошибки делают нас сильнее. Таймер перезапустится со стадии семени."
                "ja" -> "落ち込まないでください。失敗から学ぶことで人は強くなります。タイマーは種から再スタートします。"
                "ko" -> "낙담하지 마세요. 실수에서 배우며 성장하는 것입니다. 타이머가 씨앗 단계부터 다시 시작됩니다."
                "id" -> "Jangan berkecil hati. Belajar dari kesalahan membuat kita lebih kuat. Timer akan dimulai lagi dari benih."
                "tr" -> "Moralinizi bozmayın. Hatalardan ders almak bizi güçlendirir. Zamanlayıcı tohuma sıfırlanacak."
                "ur" -> "افسردہ نہ ہوں۔ غلطیوں سے سیکھ کر ہی انسان آگے بڑھتا ہے۔ ٹائمر دوبارہ بیج سے شروع ہوگا۔"
                else -> "Don't be discouraged. Learning from mistakes builds strength. Your timer will restart from seed."
            }
            "select_relapse_reason" -> when (l) {
                "bn" -> "রিলেপসের কারণ বাছাই করুন:"
                "es" -> "Selecciona la causa de la recaída:"
                "hi" -> "रिलेप्स का कारण चुनें:"
                "ar" -> "اختر سبب الانزلاق:"
                "fr" -> "Sélectionnez la cause:"
                "de" -> "Ursache auswählen:"
                "zh" -> "选择复发原因："
                "pt" -> "Selecione o motivo da recaída:"
                "ru" -> "Выберите причину срыва:"
                "ja" -> "リバウンドの原因を選択:"
                "ko" -> "재발 원인을 선택하세요:"
                "id" -> "Pilih alasan kekambuhan:"
                "tr" -> "Nedenini seçin:"
                "ur" -> "وجہ منتخب کریں:"
                else -> "Select relapse cause:"
            }
            "custom_reason_label" -> when (l) {
                "bn" -> "নির্দিষ্ট কারণ লিখুন"
                "es" -> "Especificar causa"
                "hi" -> "विशिष्ट कारण लिखें"
                "ar" -> "اكتب السبب بالتفصيل"
                "fr" -> "Spécifier la cause"
                "de" -> "Spezifische Ursache angeben"
                "zh" -> "请输入具体原因"
                "pt" -> "Especificar motivo"
                "ru" -> "Укажите причину"
                "ja" -> "具体例を入力"
                "ko" -> "구체적인 원인을 입력하세요"
                "id" -> "Tuliskan alasan spesifik"
                "tr" -> "Nedenini yazın"
                "ur" -> "خاص وجہ تحریر کریں"
                else -> "Specify custom cause"
            }
            "notes_label" -> when (l) {
                "bn" -> "কীভাবে ভবিষ্যতে এটি এড়াবেন? (নোট)"
                "es" -> "¿Cómo evitarás esto en el futuro? (Notas)"
                "hi" -> "भविष्य में इससे कैसे बचेंगे? (नोट्स)"
                "ar" -> "كيف تتجنب ذلك مستقبلاً؟ (ملاحظات)"
                "fr" -> "Comment éviter cela à l'avenir? (Notes)"
                "de" -> "Wie vermeidest du das künftig? (Notizen)"
                "zh" -> "以后如何避免该诱因？（笔记）"
                "pt" -> "Como evitar isso no futuro? (Notas)"
                "ru" -> "Как избежать этого в будущем? (Заметки)"
                "ja" -> "次回どう回避しますか？ (メモ)"
                "ko" -> "앞으로 어떻게 예방할까요? (노트)"
                "id" -> "Bagaimana cara menghindarinya kelak? (Catatan)"
                "tr" -> "Gelecekte bundan nasıl kaçınacaksınız? (Notlar)"
                "ur" -> "آئندہ اس سے کیسے بچیں گے؟ (نوٹس)"
                else -> "How to avoid this next time? (Notes)"
            }
            "notes_placeholder" -> when (l) {
                "bn" -> "যেমন: চাপ লাগলে হেঁটে আসব..."
                "es" -> "ej: Salir a caminar cuando esté estresado..."
                "hi" -> "जैसे: तनाव होने पर टहलने जाऊँगा..."
                "ar" -> "مثال: سأذهب للمشي عند الشعور بالضغط..."
                "fr" -> "ex: Faire une promenade en cas de stress..."
                "de" -> "z.B. Spazierengehen bei Stress..."
                "zh" -> "例如：感到压力时去散散步……"
                "pt" -> "ex: Caminhar quando sentir estresse..."
                "ru" -> "напр., Выйду прогуляться при стрессе..."
                "ja" -> "例: ストレスを感じたら散歩に行く..."
                "ko" -> "예: 스트레스 받을 때 산책하기..."
                "id" -> "contoh: Jalan-jalan saat stres..."
                "tr" -> "ör: Stresli olduğumda yürüyüşe çıkacağım..."
                "ur" -> "مثلاً: تناؤ ہو تو واک پر جاؤں گا..."
                else -> "e.g. Take a walk when feeling stressed..."
            }
            "confirm_reset_btn" -> when (l) {
                "bn" -> "রিসেট করুন ও পুনরায় শুরু করুন"
                "es" -> "Reiniciar Temporizador y Empezar"
                "hi" -> "रिसेट करें और पुनः शुरू करें"
                "ar" -> "إعادة الضبط والبدء من جديد"
                "fr" -> "Réinitialiser et Redémarrer"
                "de" -> "Timer zurücksetzen & Neu starten"
                "zh" -> "重置计时器并重新开始"
                "pt" -> "Reiniciar Temporizador e Recomeçar"
                "ru" -> "Сбросить таймер и начать заново"
                "ja" -> "タイマーをリセットして再スタート"
                "ko" -> "타이머 리셋 및 다시 시작"
                "id" -> "Reset Timer & Mulai Lagi"
                "tr" -> "Sıfırla ve Yeniden Başla"
                "ur" -> "ری سیٹ کریں اور دوبارہ شروع کریں"
                else -> "Reset Timer & Restart"
            }
            "cancel_btn" -> when (l) {
                "bn" -> "বাতিল"
                "es" -> "Cancelar"
                "hi" -> "रद्द करें"
                "ar" -> "إلغاء"
                "fr" -> "Annuler"
                "de" -> "Abbrechen"
                "zh" -> "取消"
                "pt" -> "Cancelar"
                "ru" -> "Отмена"
                "ja" -> "キャンセル"
                "ko" -> "취소"
                "id" -> "Batal"
                "tr" -> "İptal"
                "ur" -> "منسوخ"
                else -> "Cancel"
            }

            // Habits Screen
            "bad_habits_header" -> when (l) {
                "bn" -> "অভ্যাসসমূহ (Bad Habits)"
                "es" -> "Hábitos Rastreados"
                "hi" -> "ट्रैक की गई आदतें"
                "ar" -> "العادات المتتبعة"
                "fr" -> "Habitudes Suivies"
                "de" -> "Überwachte Gewohnheiten"
                "zh" -> "追踪中的习惯"
                "pt" -> "Hábitos Monitorados"
                "ru" -> "Отслеживаемые привычки"
                "ja" -> "追跡中の悪習慣"
                "ko" -> "추적 중인 습관"
                "id" -> "Kebiasaan Yang Ditelusuri"
                "tr" -> "Takip Edilen Alışkanlıklar"
                "ur" -> "عادات کی فہرست"
                else -> "Tracked Bad Habits"
            }
            "bad_habits_sub" -> when (l) {
                "bn" -> "আপনার নিয়ন্ত্রিত সকল অভ্যাস পর্যবেক্ষণ ও পরিচালনা করুন"
                "es" -> "Gestiona y monitorea tus hábitos a vencer"
                "hi" -> "अपनी सभी आदतों को प्रबंधित और ट्रैक करें"
                "ar" -> "إدارة ومراقبة جميع العادات التي تتغلب عليها"
                "fr" -> "Gérez vos habitudes à surmonter"
                "de" -> "Verwalte und überwache deine Gewohnheiten"
                "zh" -> "管理和掌控您正在克服的所有习惯"
                "pt" -> "Gerencie e monitore seus hábitos a vencer"
                "ru" -> "Управляйте привычками, от которых хотите избавиться"
                "ja" -> "克服したい習慣を管理・追跡します"
                "ko" -> "극복하고자 하는 습관을 관리하고 추적하세요"
                "id" -> "Kelola dan pantau semua kebiasaan Anda"
                "tr" -> "Yenmeye çalıştığınız alışkanlıkları yönetin"
                "ur" -> "اپنی تمام عادات کو کنٹرول اور ٹریک کریں"
                else -> "Manage and switch habits to conquer"
            }
            "add_habit_dialog_title" -> when (l) {
                "bn" -> "নতুন ট্র্যাকিং অভ্যাস যোগ করুন"
                "es" -> "Añadir Nuevo Hábito"
                "hi" -> "नई आदत जोड़ें"
                "ar" -> "إضافة عادة جديدة للتتبع"
                "fr" -> "Ajouter une nouvelle habitude"
                "de" -> "Neue Gewohnheit hinzufügen"
                "zh" -> "添加要克服的新习惯"
                "pt" -> "Adicionar Novo Hábito"
                "ru" -> "Добавить новую привычку"
                "ja" -> "新しい習慣の追加"
                "ko" -> "새 추적 습관 추가"
                "id" -> "Tambah Kebiasaan Baru"
                "tr" -> "Yeni Alışkanlık Ekle"
                "ur" -> "نئی عادت شامل کریں"
                else -> "Add New Bad Habit"
            }
            "select_template" -> when (l) {
                "bn" -> "টেমপ্লেট বাছাই করুন:"
                "es" -> "Seleccionar Plantilla:"
                "hi" -> "टेम्पलेट चुनें:"
                "ar" -> "اختر نموذجاً:"
                "fr" -> "Choisir un modèle:"
                "de" -> "Vorlage auswählen:"
                "zh" -> "选择模板："
                "pt" -> "Selecionar Modelo:"
                "ru" -> "Выберите шаблон:"
                "ja" -> "テンプレートを選択:"
                "ko" -> "템플릿 선택:"
                "id" -> "Pilih Templat:"
                "tr" -> "Şablon Seçin:"
                "ur" -> "ٹیمپلیٹ منتخب کریں:"
                else -> "Select Template:"
            }
            "habit_name_label" -> when (l) {
                "bn" -> "অভ্যাসের নাম"
                "es" -> "Nombre del Hábito"
                "hi" -> "आदत का नाम"
                "ar" -> "اسم العادة"
                "fr" -> "Nom de l'habitude"
                "de" -> "Name der Gewohnheit"
                "zh" -> "习惯名称"
                "pt" -> "Nome do Hábito"
                "ru" -> "Название привычки"
                "ja" -> "習慣の名称"
                "ko" -> "습관 이름"
                "id" -> "Nama Kebiasaan"
                "tr" -> "Alışkanlık Adı"
                "ur" -> "عادت کا نام"
                else -> "Habit Title"
            }
            "habit_name_ph" -> when (l) {
                "bn" -> "যেমন: ধূমপান ত্যাগ"
                "es" -> "ej: Dejar de fumar"
                "hi" -> "जैसे: धूम्रपान छोड़ना"
                "ar" -> "مثال: الإقلاع عن التدخين"
                "fr" -> "ex: Arrêter de fumer"
                "de" -> "z.B. Rauchen aufhören"
                "zh" -> "例如：戒烟"
                "pt" -> "ex: Parar de fumar"
                "ru" -> "напр., Бросить курить"
                "ja" -> "例: 禁煙"
                "ko" -> "예: 금연하기"
                "id" -> "contoh: Berhenti Merokok"
                "tr" -> "ör: Sigarayı Bırakmak"
                "ur" -> "مثلاً: تمباکو نوشی چھوڑنا"
                else -> "e.g. Quit Smoking"
            }
            "habit_desc_label" -> when (l) {
                "bn" -> "বিবরণ / লক্ষ্য"
                "es" -> "Descripción / Meta"
                "hi" -> "विवरण / लक्ष्य"
                "ar" -> "الوصف / الهدف"
                "fr" -> "Description / Objectif"
                "de" -> "Beschreibung / Ziel"
                "zh" -> "描述 / 目标"
                "pt" -> "Descrição / Meta"
                "ru" -> "Описание / Цель"
                "ja" -> "説明 / 目標"
                "ko" -> "설명 / 목표"
                "id" -> "Deskripsi / Target"
                "tr" -> "Açıklama / Hedef"
                "ur" -> "تفصیل / ہدف"
                else -> "Description / Goal"
            }
            "habit_desc_ph" -> when (l) {
                "bn" -> "যেমন: সুস্থ ও রোগমুক্ত জীবন..."
                "es" -> "ej: Vida saludable y libre..."
                "hi" -> "जैसे: स्वस्थ जीवन..."
                "ar" -> "مثال: حياة صحية ونقية..."
                "fr" -> "ex: Une vie saine..."
                "de" -> "z.B. Ein gesundes Leben..."
                "zh" -> "例如：拥有健康清爽的人生……"
                "pt" -> "ex: Uma vida saudável..."
                "ru" -> "напр., Здоровая жизнь..."
                "ja" -> "例: 健康的で新しい生活..."
                "ko" -> "예: 건강한 삶을 향하여..."
                "id" -> "contoh: Hidup sehat dan bersih..."
                "tr" -> "ör: Sağlıklı bir yaşam..."
                "ur" -> "مثلاً: ایک صحت مند زندگی..."
                else -> "e.g. Healthy smoke-free life..."
            }
            "save_btn" -> when (l) {
                "bn" -> "সংরক্ষণ করুন"
                "es" -> "Guardar"
                "hi" -> "सहेजें"
                "ar" -> "حفظ"
                "fr" -> "Enregistrer"
                "de" -> "Speichern"
                "zh" -> "保存"
                "pt" -> "Salvar"
                "ru" -> "Сохранить"
                "ja" -> "保存"
                "ko" -> "저장"
                "id" -> "Simpan"
                "tr" -> "Kaydet"
                "ur" -> "محفوظ کریں"
                else -> "Save Habit"
            }
            "active_badge" -> when (l) {
                "bn" -> "সক্রিয়"
                "es" -> "ACTIVO"
                "hi" -> "सक्रिय"
                "ar" -> "نشط"
                "fr" -> "ACTIF"
                "de" -> "AKTIV"
                "zh" -> "当前追踪"
                "pt" -> "ATIVO"
                "ru" -> "АКТИВНО"
                "ja" -> "追跡中"
                "ko" -> "추적중"
                "id" -> "AKTIF"
                "tr" -> "AKTİF"
                "ur" -> "فعال"
                else -> "ACTIVE"
            }
            "switch_habit_btn" -> when (l) {
                "bn" -> "এই অভ্যাসটি ট্র্যাকিং করুন"
                "es" -> "Rastrear este hábito"
                "hi" -> "इस आदत को ट्रैक करें"
                "ar" -> "تتبع هذه العادة"
                "fr" -> "Suivre cette habitude"
                "de" -> "Diese Gewohnheit verfolgen"
                "zh" -> "切换并追踪此习惯"
                "pt" -> "Rastrear este hábito"
                "ru" -> "Отслеживать эту привычку"
                "ja" -> "この習慣をトラッキング"
                "ko" -> "이 습관 추적하기"
                "id" -> "Lacak kebiasaan ini"
                "tr" -> "Bu alışkanlığı takip et"
                "ur" -> "اس عادت کو ٹریک کریں"
                else -> "Switch to this habit"
            }
            "delete_habit_title" -> when (l) {
                "bn" -> "অভ্যাসটি মুছে ফেলবেন?"
                "es" -> "¿Eliminar hábito?"
                "hi" -> "क्या आदत हटाएं?"
                "ar" -> "هل تريد حذف العادة؟"
                "fr" -> "Supprimer l'habitude?"
                "de" -> "Gewohnheit löschen?"
                "zh" -> "要删除此习惯吗？"
                "pt" -> "Excluir hábito?"
                "ru" -> "Удалить привычку?"
                "ja" -> "習慣を削除しますか？"
                "ko" -> "습관을 삭제하시겠습니까?"
                "id" -> "Hapus kebiasaan?"
                "tr" -> "Alışkanlık silinsin mi?"
                "ur" -> "عادت کو حذف کریں؟"
                else -> "Delete Habit?"
            }
            "delete_habit_msg" -> when (l) {
                "bn" -> "আপনি কি নিশ্চিত যে আপনি এই অভ্যাসটি এবং এর সকল রিলেপস ইতিহাস মুছে ফেলতে চান?"
                "es" -> "¿Estás seguro de que deseas eliminar este hábito y todo su historial de recaídas?"
                "hi" -> "क्या आप निश्चित हैं कि आप इस आदत और इसके सभी इतिहास को हटाना चाहते हैं?"
                "ar" -> "هل أنت تأكد من أنك تريد حذف هذه العادة وجميع سجلات الانزلاق الخاصة بها؟"
                "fr" -> "Êtes-vous sûr de vouloir supprimer cette habitude et tout son historique?"
                "de" -> "Bist du sicher, dass du diese Gewohnheit und ihre Historie löschen möchtest?"
                "zh" -> "您确定要删除此习惯及其所有历史记录吗？"
                "pt" -> "Tem certeza de que deseja excluir este hábito e todo o seu histórico?"
                "ru" -> "Вы уверены, что хотите удалить эту привычку и всю ее историю?"
                "ja" -> "この習慣とすべての履歴を削除してもよろしいですか？"
                "ko" -> "이 습관과 모든 기록을 삭제하시겠습니까?"
                "id" -> "Apakah Anda yakin ingin menghapus kebiasaan ini beserta seluruh riwayatnya?"
                "tr" -> "Bu alışkanlığı ve tüm geçmişini silmek istediğinizden emin misiniz?"
                "ur" -> "کیا آپ واقعی اس عادت اور اس کی تمام ہسٹری کو حذف کرنا چاہتے ہیں؟"
                else -> "Are you sure you want to delete this habit and all its relapse history?"
            }
            "delete_btn" -> when (l) {
                "bn" -> "মুছে ফেলুন"
                "es" -> "Eliminar"
                "hi" -> "हटाएं"
                "ar" -> "حذف"
                "fr" -> "Supprimer"
                "de" -> "Löschen"
                "zh" -> "删除"
                "pt" -> "Excluir"
                "ru" -> "Удалить"
                "ja" -> "削除"
                "ko" -> "삭제"
                "id" -> "Hapus"
                "tr" -> "Sil"
                "ur" -> "حذف کریں"
                else -> "Delete"
            }

            // Stats Screen
            "stats_screen_title" -> when (l) {
                "bn" -> "পরিসংখ্যান ও রেকর্ড (Statistics)"
                "es" -> "Estadísticas y Registros"
                "hi" -> "आंकड़े और रिकॉर्ड"
                "ar" -> "الإحصائيات والسجلات"
                "fr" -> "Statistiques et Historique"
                "de" -> "Statistiken & Aufzeichnungen"
                "zh" -> "数据与统计"
                "pt" -> "Estatísticas e Registros"
                "ru" -> "Статистика и рекорды"
                "ja" -> "統計と記録"
                "ko" -> "통계 및 기록"
                "id" -> "Statistik & Catatan"
                "tr" -> "İstatistikler ve Kayıtlar"
                "ur" -> "اعداد و شمار"
                else -> "Statistics & Records"
            }
            "stats_screen_sub" -> when (l) {
                "bn" -> "%s মুক্ত জীবনের অগ্রগতি বিশ্লেষণ"
                "es" -> "Análisis del progreso hacia una vida libre de %s"
                "hi" -> "%s मुक्त जीवन की प्रगति का विश्लेषण"
                "ar" -> "تحليل التقدم نحو حياة خالية من %s"
                "fr" -> "Analyse du progrès vers une vie sans %s"
                "de" -> "Fortschrittsanalyse für ein Leben ohne %s"
                "zh" -> "%s 习惯摆脱分析"
                "pt" -> "Análise do progresso sem %s"
                "ru" -> "Анализ прогресса жизни без %s"
                "ja" -> "%s からの解放の進捗分析"
                "ko" -> "%s 없는 삶의 진전 분석"
                "id" -> "Analisis kemajuan bebas %s"
                "tr" -> "%s içermeyen yaşam ilerleme analizi"
                "ur" -> "%s سے پاک زندگی کی پیشرفت"
                else -> "Progress analysis for a %s-free life"
            }
            "current_streak_title" -> when (l) {
                "bn" -> "বর্তমান স্ট্রিক"
                "es" -> "Racha Actual"
                "hi" -> "वर्तमान स्ट्रीक"
                "ar" -> "السلسلة الحالية"
                "fr" -> "Série Actuelle"
                "de" -> "Aktueller Serie"
                "zh" -> "当前连续天数"
                "pt" -> "Sequência Atual"
                "ru" -> "Текущая серия"
                "ja" -> "現在のストリーク"
                "ko" -> "현재 연속 기록"
                "id" -> "Runtutan Saat Ini"
                "tr" -> "Mevcut Seri"
                "ur" -> "موجودہ سلسلہ"
                else -> "Current Streak"
            }
            "longest_streak_title" -> when (l) {
                "bn" -> "সর্বোচ্চ স্ট্রিক"
                "es" -> "Racha Más Larga"
                "hi" -> "सर्वश्रेष्ठ स्ट्रीक"
                "ar" -> "أطول سلسلة"
                "fr" -> "Record de Série"
                "de" -> "Beste Serie"
                "zh" -> "最高连续天数"
                "pt" -> "Maior Sequência"
                "ru" -> "Рекордная серия"
                "ja" -> "最长ストリーク"
                "ko" -> "최고 연속 기록"
                "id" -> "Runtutan Terpanjang"
                "tr" -> "En Uzun Seri"
                "ur" -> "طویل ترین سلسلہ"
                else -> "Longest Streak"
            }
            "total_relapses_title" -> when (l) {
                "bn" -> "মোট রিলেপস"
                "es" -> "Recaídas Totales"
                "hi" -> "कुल रिलेप्स"
                "ar" -> "إجمالي الانزلاقات"
                "fr" -> "Total Rechutes"
                "de" -> "Gesamte Rückfälle"
                "zh" -> "复发总次数"
                "pt" -> "Total de Recaídas"
                "ru" -> "Всего срывов"
                "ja" -> "通算リバウンド数"
                "ko" -> "총 재발 횟수"
                "id" -> "Total Kekambuhan"
                "tr" -> "Toplam Tekrarlama"
                "ur" -> "کل غلطیاں"
                else -> "Total Relapses"
            }
            "avg_streak_title" -> when (l) {
                "bn" -> "গড় স্থায়িত্ব"
                "es" -> "Promedio de Racha"
                "hi" -> "औसत स्ट्रीक"
                "ar" -> "متوسط السلسلة"
                "fr" -> "Moyenne de Série"
                "de" -> "Durchschnittliche Serie"
                "zh" -> "平均坚持天数"
                "pt" -> "Média da Sequência"
                "ru" -> "Средняя серия"
                "ja" -> "平均ストリーク"
                "ko" -> "평균 유지 기간"
                "id" -> "Rata-rata Runtutan"
                "tr" -> "Ortalama Seri"
                "ur" -> "اوسط سلسلہ"
                else -> "Average Streak"
            }
            "days_unit" -> when (l) {
                "bn" -> "দিন"
                "es" -> "días"
                "hi" -> "दिन"
                "ar" -> "أيام"
                "fr" -> "jours"
                "de" -> "Tage"
                "zh" -> "天"
                "pt" -> "dias"
                "ru" -> "дн."
                "ja" -> "日"
                "ko" -> "일"
                "id" -> "hari"
                "tr" -> "gün"
                "ur" -> "دن"
                else -> "Days"
            }
            "times_unit" -> when (l) {
                "bn" -> "বার"
                "es" -> "veces"
                "hi" -> "बार"
                "ar" -> "مرات"
                "fr" -> "fois"
                "de" -> "Mal"
                "zh" -> "次"
                "pt" -> "vezes"
                "ru" -> "раз"
                "ja" -> "回"
                "ko" -> "회"
                "id" -> "kali"
                "tr" -> "kez"
                "ur" -> "بار"
                else -> "Times"
            }
            "trigger_breakdown_header" -> when (l) {
                "bn" -> "রিলেপস বা ভুলের কারণ বিশ্লেষণ"
                "es" -> "Análisis de Causas de Recaída"
                "hi" -> "रिलेप्स के कारणों का विश्लेषण"
                "ar" -> "تحليل أسباب الانزلاق"
                "fr" -> "Analyse des facteurs déclencheurs"
                "de" -> "Analyse der Rückfallursachen"
                "zh" -> "复发诱因分析"
                "pt" -> "Análise de Causas de Recaída"
                "ru" -> "Анализ причин срывов"
                "ja" -> "リバウンド原因の分析"
                "ko" -> "재발 원인 분석"
                "id" -> "Analisis Pemicu Kekambuhan"
                "tr" -> "Tekrarlama Nedenleri Analizi"
                "ur" -> "غلطیوں کی وجوہات کا تجزیہ"
                else -> "Relapse Trigger Analysis"
            }
            "no_relapses_yet" -> when (l) {
                "bn" -> "এখনও কোনো রিলেপস রেকর্ড নেই! এভাবেই এগিয়ে যান! 🌱"
                "es" -> "¡Sin recaídas registradas todavía! ¡Sigue así! 🌱"
                "hi" -> "अभी तक कोई रिलेप्स रिकॉर्ड नहीं है! ऐसे ही आगे बढ़ते रहें! 🌱"
                "ar" -> "لا يوجد انزلاقات مسجلة حتى الآن! استمر في التقدم! 🌱"
                "fr" -> "Aucune rechute enregistrée! Continuez ainsi! 🌱"
                "de" -> "Noch keine Rückfälle verzeichnet! Weiter so! 🌱"
                "zh" -> "目前零复发！请继续保持！🌱"
                "pt" -> "Nenhuma recaída registrada ainda! Continue assim! 🌱"
                "ru" -> "Срывов пока не зафиксировано! Так держать! 🌱"
                "ja" -> "リバウンド記録はありません！この調子で頑張りましょう！🌱"
                "ko" -> "아직 재발 기록이 없습니다! 이대로 계속 나아가세요! 🌱"
                "id" -> "Belum ada catatan kambuh! Pertahankan! 🌱"
                "tr" -> "Henüz kaydedilmiş bir tekrarlama yok! Böyle devam edin! 🌱"
                "ur" -> "ابھی تک کوئی غلطی ریکارڈ نہیں ہے! ایسے ہی آگے بڑھیں! 🌱"
                else -> "No relapses recorded yet! Keep up the great work! 🌱"
            }
            "relapse_history_header" -> when (l) {
                "bn" -> "রিলেপসের ইতিহাস ও ডায়রি"
                "es" -> "Historial de Recaídas y Notas"
                "hi" -> "रिलेप्स इतिहास और नोट्स"
                "ar" -> "سجل الانزلاقات والملاحظات"
                "fr" -> "Historique des rechutes et notes"
                "de" -> "Rückfallhistorie & Notizen"
                "zh" -> "复发历史与日志"
                "pt" -> "Histórico de Recaídas e Notas"
                "ru" -> "История срывов и заметки"
                "ja" -> "リバウンドの履歴とメモ"
                "ko" -> "재발 기록 및 노트"
                "id" -> "Riwayat Kekambuhan & Catatan"
                "tr" -> "Tekrarlama Geçmişi ve Notlar"
                "ur" -> "غلطیوں کی ہسٹری"
                else -> "Relapse Log & Notes History"
            }
            "no_history_clean" -> when (l) {
                "bn" -> "আপনার যাত্রাপথ একদম সুশৃঙ্খল ও কলঙ্কমুক্ত!"
                "es" -> "¡Tu camino está completamente limpio y libre de recaídas!"
                "hi" -> "आपकी यात्रा पूरी तरह से स्वच्छ और अनुशासित है!"
                "ar" -> "مسيرتك نقية تماماً وخالية من أي تعثرات!"
                "fr" -> "Votre parcours est totalement propre!"
                "de" -> "Dein Weg ist völlig sauber und vorbildlich!"
                "zh" -> "您的坚守之路非常纯粹，保持着完全克制的完美记录！"
                "pt" -> "Sua jornada está totalmente limpa e disciplinada!"
                "ru" -> "Ваш путь чист от срывов! Потрясающая дисциплина!"
                "ja" -> "あなたの道のりは完全にクリーンです！"
                "ko" -> "당신의 여정은 매우 깨끗하고 완벽합니다!"
                "id" -> "Perjalanan Anda bersih tanpa kekambuhan!"
                "tr" -> "Yolculuğunuz tamamen temiz ve kusursuz!"
                "ur" -> "آپ کا سفر مکمل طور پر صاف ستھرا ہے!"
                else -> "Your journey is completely clean and relapse-free!"
            }
            "no_relapse_logged" -> when (l) {
                "bn" -> "কোনো রিলেপস ইতিহাস পাওয়া যায়নি"
                "es" -> "No se encontraron registros de recaídas"
                "hi" -> "कोई रिलेप्स रिकॉर्ड नहीं मिला"
                "ar" -> "لم يتم العثور على سجلات انزلاق"
                "fr" -> "Aucun historique de rechute"
                "de" -> "Keine Rückfalleinträge"
                "zh" -> "未查询到复发记录"
                "pt" -> "Nenhum histórico de recaída"
                "ru" -> "Записи о срывах отсутствуют"
                "ja" -> "リバウンド記録はありません"
                "ko" -> "재발 기록이 없습니다"
                "id" -> "Tidak ada riwayat kambuh"
                "tr" -> "Tekrarlama kaydı bulunamadı"
                "ur" -> "کوئی ریکارڈ نہیں ملا"
                else -> "No relapse history logged"
            }
            "streak_going_strong" -> when (l) {
                "bn" -> "আপনার আত্মনিয়ন্ত্রণ ও সংকল্প প্রশংসনীয়!"
                "es" -> "¡Tu autocontrol y compromiso son admirables!"
                "hi" -> "आपका आत्म-नियंत्रण सराहनीय है!"
                "ar" -> "ضبط نفسك والتزامك رائع للغاية!"
                "fr" -> "Votre discipline est admirable!"
                "de" -> "Deine Selbstbeherrschung ist vorbildlich!"
                "zh" -> "您的自律与意志力令人敬佩！"
                "pt" -> "Seu autocontrole é admirável!"
                "ru" -> "Ваш самоконтроль достоин уважения!"
                "ja" -> "あなたの自律心は素晴らしいです！"
                "ko" -> "당신의 자기통제력은 훌륭합니다!"
                "id" -> "Kontrol diri Anda sangat luar biasa!"
                "tr" -> "Özdenetiminiz takdire şayan!"
                "ur" -> "آپ کا ضبط نفس قابل تعریف ہے!"
                else -> "Your self-control and commitment are admirable!"
            }

            // Profile Screen
            "profile_avatars_header" -> when (l) {
                "bn" -> "প্রোফাইল পিকচার ও অবতারস"
                "es" -> "Avatares de Perfil"
                "hi" -> "प्रोफ़ाइल अवतार"
                "ar" -> "الصورة الشخصية والرمزية"
                "fr" -> "Avatars de profil"
                "de" -> "Profil-Avatare"
                "zh" -> "个人头像"
                "pt" -> "Avatares de Perfil"
                "ru" -> "Аватары профиля"
                "ja" -> "プロフィールアバター"
                "ko" -> "프로필 아바타"
                "id" -> "Avatar Profil"
                "tr" -> "Profil Avatarları"
                "ur" -> "پروفائل اوتار"
                else -> "Profile Avatars"
            }
            "profile_themes_header" -> when (l) {
                "bn" -> "অ্যাপের থিম কালারসমূহ"
                "es" -> "Colores de Tema de la App"
                "hi" -> "ऐप के थीम रंग"
                "ar" -> "ألوان مظهر التطبيق"
                "fr" -> "Couleurs de thème d'application"
                "de" -> "App-Design-Farben"
                "zh" -> "应用主题配色"
                "pt" -> "Cores do Tema do App"
                "ru" -> "Цветовые темы приложения"
                "ja" -> "アプリテーマカラー"
                "ko" -> "앱 테마 색상"
                "id" -> "Warna Tema Aplikasi"
                "tr" -> "Uygulama Tema Renkleri"
                "ur" -> "ایپ تھیم کے رنگ"
                else -> "App Theme Colors"
            }
            "profile_skins_header" -> when (l) {
                "bn" -> "বীজ ও গাছের স্কিনসমূহ"
                "es" -> "Skins de Árbol y Semilla"
                "hi" -> "वृक्ष और बीज की खाल"
                "ar" -> "مظاهر الأشجار والبذور"
                "fr" -> "Thèmes d'Arbres et Graines"
                "de" -> "Baum- & Samen-Skins"
                "zh" -> "树木与种子外观"
                "pt" -> "Skins de Árvores e Sementes"
                "ru" -> "Скины деревьев и семян"
                "ja" -> "ツリー＆シードのスキン"
                "ko" -> "나무 & 씨앗 스킨"
                "id" -> "Skin Pohon & Benih"
                "tr" -> "Ağaç ve Tohum Görünümleri"
                "ur" -> "درخت اور بیج کے اسکن"
                else -> "Tree & Seed Skins"
            }
            "unlock_via_ad_streak" -> when (l) {
                "bn" -> "রেকর্ড বা অ্যাড দেখে আনলক করুন"
                "es" -> "Desbloquea con racha o anuncios"
                "hi" -> "स्ट्रीक या विज्ञापन से अनलॉक करें"
                "ar" -> "افتح بالإنجاز أو الإعلانات"
                "fr" -> "Débloquer via série ou pub"
                "de" -> "Freischalten via Serie oder Werbung"
                "zh" -> "通过连续打卡或观看广告解锁"
                "pt" -> "Desbloqueie com racha ou anúncio"
                "ru" -> "Разблокируйте за серию или рекламу"
                "ja" -> "記録または広告視聴で解除"
                "ko" -> "기록 또는 광고 시청으로 해제"
                "id" -> "Buka dengan rekor atau iklan"
                "tr" -> "Seri veya reklam ile kilidi açın"
                "ur" -> "ریکارڈ یا اشتہار سے انلاک کریں"
                else -> "Unlock via streak or ad"
            }
            "watch_ad_unlock" -> when (l) {
                "bn" -> "অ্যাড দেখে আনলক করুন"
                "es" -> "Ver Anuncio para Desbloquear"
                "hi" -> "विज्ञापन देखकर अनलॉक करें"
                "ar" -> "شاهد إعلاناً للفتح"
                "fr" -> "Regarder une pub pour débloquer"
                "de" -> "Werbung ansehen zum Freischalten"
                "zh" -> "观看广告免费解锁"
                "pt" -> "Assistir Anúncio para Desbloquear"
                "ru" -> "Смотреть рекламу для разблокировки"
                "ja" -> "動画広告を見て解除"
                "ko" -> "광고 보고 해제"
                "id" -> "Tonton Iklan untuk Buka"
                "tr" -> "Açmak için Reklam İzle"
                "ur" -> "اشتہار دیکھ کر انلاک کریں"
                else -> "Watch Ad to Unlock"
            }
            "req_days_streak" -> when (l) {
                "bn" -> "প্রয়োজন %d দিনের স্ট্রিক"
                "es" -> "Requiere racha de %d días"
                "hi" -> "%d दिनों की स्ट्रीक आवश्यक"
                "ar" -> "يتطلب سلسلة %d أيام"
                "fr" -> "Nécessite une série de %d jours"
                "de" -> "Erfordert %d Tage Serie"
                "zh" -> "需要连续坚持 %d 天"
                "pt" -> "Exige sequência de %d dias"
                "ru" -> "Требуется серия в %d дней"
                "ja" -> "%d日間のストリークが必要"
                "ko" -> "%d일 연속 기록 필요"
                "id" -> "Perlu rekor %d hari"
                "tr" -> "%d günlük seri gerektirir"
                "ur" -> "%d دن کا سلسلہ درکار"
                else -> "Requires %d Days Streak"
            }
            "selected_badge" -> when (l) {
                "bn" -> "নির্বাচিত"
                "es" -> "Seleccionado"
                "hi" -> "चयनित"
                "ar" -> "محدد"
                "fr" -> "Sélectionné"
                "de" -> "Ausgewählt"
                "zh" -> "已选择"
                "pt" -> "Selecionado"
                "ru" -> "Выбрано"
                "ja" -> "選択中"
                "ko" -> "선택됨"
                "id" -> "Terpilih"
                "tr" -> "Seçildi"
                "ur" -> "منتخب"
                else -> "Selected"
            }
            "select_btn" -> when (l) {
                "bn" -> "বাছাই করুন"
                "es" -> "Seleccionar"
                "hi" -> "चुनें"
                "ar" -> "اختيار"
                "fr" -> "Choisir"
                "de" -> "Wählen"
                "zh" -> "使用"
                "pt" -> "Selecionar"
                "ru" -> "Выбрать"
                "ja" -> "選択"
                "ko" -> "선택"
                "id" -> "Pilih"
                "tr" -> "Seç"
                "ur" -> "منتخب کریں"
                else -> "Select"
            }

            "edit_profile_title" -> when (l) {
                "bn" -> "প্রোফাইল তথ্য পরিবর্তন"
                "es" -> "Editar Información del Perfil"
                "hi" -> "प्रोफ़ाइल जानकारी संपादित करें"
                "ar" -> "تعديل معلومات الملف الشخصي"
                "fr" -> "Modifier les informations du profil"
                "de" -> "Profilinformationen bearbeiten"
                "zh" -> "编辑个人资料"
                "pt" -> "Editar Informações do Perfil"
                "ru" -> "Редактировать профиль"
                "ja" -> "プロフィール情報を編集"
                "ko" -> "프로필 정보 수정"
                "id" -> "Edit Informasi Profil"
                "tr" -> "Profil Bilgilerini Düzenle"
                "ur" -> "پروفائل کی معلومات میں ترمیم کریں"
                else -> "Edit Profile Information"
            }
            "your_name_label" -> when (l) {
                "bn" -> "আপনার নাম"
                "es" -> "Tu Nombre"
                "hi" -> "आपका नाम"
                "ar" -> "اسمك"
                "fr" -> "Votre nom"
                "de" -> "Dein Name"
                "zh" -> "您的名字"
                "pt" -> "Seu Nome"
                "ru" -> "Ваше имя"
                "ja" -> "あなたの名前"
                "ko" -> "당신의 이름"
                "id" -> "Nama Anda"
                "tr" -> "Adınız"
                "ur" -> "آپ کا نام"
                else -> "Your Name"
            }
            "your_bio_label" -> when (l) {
                "bn" -> "আপনার সংকল্প / স্ট্যাটাস"
                "es" -> "Tu Resolución / Estado"
                "hi" -> "आपकी स्थिति / संकल्प"
                "ar" -> "سيرتك الذاتية / القرار"
                "fr" -> "Votre résolution / statut"
                "de" -> "Dein Vorsatz / Status"
                "zh" -> "您的决心 / 状态"
                "pt" -> "Sua Resolução / Status"
                "ru" -> "Ваш статус / цель"
                "ja" -> "あなたの抱負 / ステータス"
                "ko" -> "당신의 결심 / 상태"
                "id" -> "Resolusi / Status Anda"
                "tr" -> "Kararlılığınız / Durumunuz"
                "ur" -> "آپ کا عزم / اسٹیٹس"
                else -> "Your Bio / Resolution"
            }
            "save_profile_btn" -> when (l) {
                "bn" -> "সংরক্ষণ করুন"
                "es" -> "Guardar Perfil"
                "hi" -> "प्रोफ़ाइल सहेजें"
                "ar" -> "حفظ الملف الشخصي"
                "fr" -> "Enregistrer le profil"
                "de" -> "Profil speichern"
                "zh" -> "保存个人资料"
                "pt" -> "Salvar Perfil"
                "ru" -> "Сохранить профиль"
                "ja" -> "プロフィールを保存"
                "ko" -> "프로필 저장"
                "id" -> "Simpan Profil"
                "tr" -> "Profili Kaydet"
                "ur" -> "پروفائل محفوظ کریں"
                else -> "Save Profile"
            }
            "best_record_label" -> when (l) {
                "bn" -> "সর্বোচ্চ রেকর্ড"
                "es" -> "Mejor Récord"
                "hi" -> "सर्वश्रेष्ठ रिकॉर्ड"
                "ar" -> "أفضل إنجاز"
                "fr" -> "Meilleur record"
                "de" -> "Bester Rekord"
                "zh" -> "最佳记录"
                "pt" -> "Melhor Recorde"
                "ru" -> "Лучший рекорд"
                "ja" -> "最高記録"
                "ko" -> "최고 기록"
                "id" -> "Rekor Terbaik"
                "tr" -> "En İyi Rekor"
                "ur" -> "بہترین ریکارڈ"
                else -> "Best Record"
            }
            "current_streak_label" -> when (l) {
                "bn" -> "বর্তমান স্ট্রাইক"
                "es" -> "Racha Actual"
                "hi" -> "वर्तमान स्ट्रीक"
                "ar" -> "السلسلة الحالية"
                "fr" -> "Série actuelle"
                "de" -> "Aktueller Streak"
                "zh" -> "当前连胜"
                "pt" -> "Racha Atual"
                "ru" -> "Текущая серия"
                "ja" -> "現在のストリーク"
                "ko" -> "현재 스트릭"
                "id" -> "Streak Saat Ini"
                "tr" -> "Mevcut Seri"
                "ur" -> "موجودہ سلسلہ"
                else -> "Current Streak"
            }
            "app_language_title" -> when (l) {
                "bn" -> "🌐 অ্যাপের ভাষা (App Language)"
                "es" -> "🌐 Idioma de la Aplicación"
                "hi" -> "🌐 ऐप की भाषा (App Language)"
                "ar" -> "🌐 لغة التطبيق"
                "fr" -> "🌐 Langue de l'application"
                "de" -> "🌐 App-Sprache"
                "zh" -> "🌐 应用语言"
                "pt" -> "🌐 Idioma do Aplicativo"
                "ru" -> "🌐 Язык приложения"
                "ja" -> "🌐 アプリの言語"
                "ko" -> "🌐 앱 언어"
                "id" -> "🌐 Bahasa Aplikasi"
                "tr" -> "🌐 Uygulama Dili"
                "ur" -> "🌐 ایپ کی زبان"
                else -> "🌐 App Language"
            }
            "in_use_label" -> when (l) {
                "bn" -> "ব্যবহার হচ্ছে"
                "es" -> "En uso"
                "hi" -> "उपयोग में"
                "ar" -> "قيد الاستخدام"
                "fr" -> "Utilisé"
                "de" -> "In Verwendung"
                "zh" -> "使用中"
                "pt" -> "Em uso"
                "ru" -> "Используется"
                "ja" -> "使用中"
                "ko" -> "사용 중"
                "id" -> "Digunakan"
                "tr" -> "Kullanımda"
                "ur" -> "استعمال میں"
                else -> "In Use"
            }
            "unlocked_label" -> when (l) {
                "bn" -> "আনলকড"
                "es" -> "Desbloqueado"
                "hi" -> "अनलाक्ड"
                "ar" -> "مفتوح"
                "fr" -> "Débloqué"
                "de" -> "Freigeschaltet"
                "zh" -> "已解锁"
                "pt" -> "Desbloqueado"
                "ru" -> "Разблокировано"
                "ja" -> "解除済み"
                "ko" -> "해제됨"
                "id" -> "Terbuka"
                "tr" -> "Kilit Açıldı"
                "ur" -> "انلاک شدہ"
                else -> "Unlocked"
            }
            "req_record_days" -> when (l) {
                "bn" -> "%d দিনের রেকর্ড"
                "es" -> "Récord de %d días"
                "hi" -> "%d दिनों का रिकॉर्ड"
                "ar" -> "سلسلة %d أيام"
                "fr" -> "Record de %d jours"
                "de" -> "%d Tage Rekord"
                "zh" -> "%d 天记录"
                "pt" -> "Recorde de %d dias"
                "ru" -> "Рекорд %d дней"
                "ja" -> "%d日記録"
                "ko" -> "%d일 기록"
                "id" -> "Rekor %d hari"
                "tr" -> "%d günlük rekor"
                "ur" -> "%d دن کا ریکارڈ"
                else -> "%d Days Record"
            }
            "watch_ad_btn" -> when (l) {
                "bn" -> "অ্যাড দেখুন"
                "es" -> "Ver Anuncio"
                "hi" -> "विज्ञापन देखें"
                "ar" -> "شاهد إعلان"
                "fr" -> "Voir pub"
                "de" -> "Werbung ansehen"
                "zh" -> "观看广告"
                "pt" -> "Ver Anúncio"
                "ru" -> "Смотреть рекламу"
                "ja" -> "広告を見る"
                "ko" -> "광고 보기"
                "id" -> "Tonton Iklan"
                "tr" -> "Reklam İzle"
                "ur" -> "اشتہار دیکھیں"
                else -> "Watch Ad"
            }
            "currently_active_label" -> when (l) {
                "bn" -> "বর্তমানে সক্রিয়"
                "es" -> "Tema Activo"
                "hi" -> "वर्तमान में सक्रिय"
                "ar" -> "السمة النشطة"
                "fr" -> "Actuellement actif"
                "de" -> "Derzeit aktiv"
                "zh" -> "当前激活"
                "pt" -> "Ativo no momento"
                "ru" -> "Сейчас активно"
                "ja" -> "現在アクティブ"
                "ko" -> "현재 활성화됨"
                "id" -> "Aktif saat ini"
                "tr" -> "Şu An Etkin"
                "ur" -> "فی الحال فعال"
                else -> "Currently Active"
            }
            "tap_to_apply_label" -> when (l) {
                "bn" -> "ব্যবহার করতে ট্যাপ করুন"
                "es" -> "Toca para aplicar"
                "hi" -> "उपयोग करने के लिए टैप करें"
                "ar" -> "انقر للاستخدام"
                "fr" -> "Appuyez pour appliquer"
                "de" -> "Tippen zum Anwenden"
                "zh" -> "点击应用"
                "pt" -> "Toque para aplicar"
                "ru" -> "Нажмите для применения"
                "ja" -> "タップして適用"
                "ko" -> "적용하려면 탭하세요"
                "id" -> "Ketuk untuk menerapkan"
                "tr" -> "Uygulamak için dokunun"
                "ur" -> "لاگو کرنے کے لیے ٹیپ کریں"
                else -> "Tap to Apply"
            }
            "requires_streak_days" -> when (l) {
                "bn" -> "প্রয়োজন: %d দিনের রেকর্ড"
                "es" -> "Requiere racha de %d días"
                "hi" -> "आवश्यक: %d दिनों का रिकॉर्ड"
                "ar" -> "يتطلب سلسلة %d أيام"
                "fr" -> "Nécessite une série de %d jours"
                "de" -> "Erfordert %d Tage Streak"
                "zh" -> "需要连续 %d 天"
                "pt" -> "Requer racha de %d dias"
                "ru" -> "Требуется серия %d дней"
                "ja" -> "%d日間のストリークが必要"
                "ko" -> "%d일 스트릭 필요"
                "id" -> "Perlu rekor %d hari"
                "tr" -> "%d günlük seri gerekli"
                "ur" -> "%d دن کا سلسلہ درکار"
                else -> "Requires %d Days Streak"
            }
            "ad_unlock_btn" -> when (l) {
                "bn" -> "এড দেখে আনলক"
                "es" -> "Ver Anuncio para Desbloquear"
                "hi" -> "विज्ञापन अनलॉक"
                "ar" -> "فتح بإعلان"
                "fr" -> "Débloquer via pub"
                "de" -> "Werbung freischalten"
                "zh" -> "广告解锁"
                "pt" -> "Desbloquear com anúncio"
                "ru" -> "Разблокировать рекламой"
                "ja" -> "広告で解除"
                "ko" -> "광고 해제"
                "id" -> "Buka dengan iklan"
                "tr" -> "Reklamla Aç"
                "ur" -> "اشتہار سے انلاک"
                else -> "Ad Unlock"
            }
            "locked_streak_or_ad" -> when (l) {
                "bn" -> "লকড: %d দিন অথবা এড দেখুন"
                "es" -> "Bloqueado: %d días o ver anuncio"
                "hi" -> "लॉक: %d दिन या विज्ञापन देखें"
                "ar" -> "مغلق: %d أيام أو شاهد إعلان"
                "fr" -> "Verrouillé: %d jours ou regarder une pub"
                "de" -> "Gesperrt: %d Tage oder Werbung sehen"
                "zh" -> "已锁定：%d 天或观看广告"
                "pt" -> "Bloqueado: %d dias ou ver anúncio"
                "ru" -> "Заблокировано: %d дней или реклама"
                "ja" -> "ロック中: %d日または広告視聴"
                "ko" -> "잠김: %d일 또는 광고 시청"
                "id" -> "Terkunci: %d hari atau tonton iklan"
                "tr" -> "Kilitli: %d gün veya reklam izle"
                "ur" -> "مقفل: %d دن یا اشتہار دیکھیں"
                else -> "Locked: %d Days or Watch Ad"
            }
            "apply_btn" -> when (l) {
                "bn" -> "ব্যবহার করুন"
                "es" -> "Aplicar"
                "hi" -> "उपयोग करें"
                "ar" -> "تطبيق"
                "fr" -> "Appliquer"
                "de" -> "Anwenden"
                "zh" -> "应用"
                "pt" -> "Aplicar"
                "ru" -> "Применить"
                "ja" -> "適用"
                "ko" -> "적용"
                "id" -> "Terapkan"
                "tr" -> "Uygula"
                "ur" -> "لاگو کریں"
                else -> "Apply"
            }
            "non_skippable_ad_title" -> when (l) {
                "bn" -> "নন-স্কিপেবল রিওয়ার্ডেড এড"
                "es" -> "Anuncio de Video Recompensado"
                "hi" -> "गैर-स्किप करने योग्य पुरस्कृत विज्ञापन"
                "ar" -> "إعلان فيديو مكافأة غير قابل للتخطي"
                "fr" -> "Publicité vidéo avec récompense"
                "de" -> "Nicht überspringbare Belohnungswerbung"
                "zh" -> "不可跳过的奖励广告"
                "pt" -> "Anúncio Recompensado Não Ignorável"
                "ru" -> "Вознаграждаемая видеореклама"
                "ja" -> "スキップ不可のリワード広告"
                "ko" -> "건너뛸 수 없는 보상형 광고"
                "id" -> "Iklan Berhadiah Tanpa Skip"
                "tr" -> "Atlanamayan Ödüllü Reklam"
                "ur" -> "غیر اسکیپ ایبل ریوارڈڈ اشتہار"
                else -> "Non-Skippable Rewarded Ad"
            }
            "sponsored_video_desc" -> when (l) {
                "bn" -> "পুরস্কার আনলক স্পন্সরড ভিডিও"
                "es" -> "Video Patrocinado para Recompensa"
                "hi" -> "पुरस्कार अनलॉक प्रायोजित वीडियो"
                "ar" -> "فيديو برعاية لفتح المكافأة"
                "fr" -> "Vidéo sponsorisée pour débloquer"
                "de" -> "Gesponsertes Belohnungsvideo"
                "zh" -> "赞助奖励视频"
                "pt" -> "Vídeo Patrocinado de Recompensa"
                "ru" -> "Спонсорское видео с наградой"
                "ja" -> "特典解禁スポンサー動画"
                "ko" -> "보상 해제 후원 비디오"
                "id" -> "Video Sponsor Berhadiah"
                "tr" -> "Ödül Kilit Açma Sponsorlu Video"
                "ur" -> "انعام انلاک اسپانسر شدہ ویڈیو"
                else -> "Sponsored Reward Video"
            }
            "full_watch_required" -> when (l) {
                "bn" -> "🔒 নন-স্কিপেবল (সম্পূর্ণ দেখা বাধ্যতামূলক)"
                "es" -> "🔒 Obligatorio ver completo"
                "hi" -> "🔒 पूरा देखना अनिवार्य है"
                "ar" -> "🔒 مشاهدة كاملة إجبارية"
                "fr" -> "🔒 Visionnage complet obligatoire"
                "de" -> "🔒 Vollständiges Ansehen erforderlich"
                "zh" -> "🔒 必须完整观看"
                "pt" -> "🔒 Visualização completa obrigatória"
                "ru" -> "🔒 Обязателен полный просмотр"
                "ja" -> "🔒 視聴完了が必須です"
                "ko" -> "🔒 전체 시청 필수"
                "id" -> "🔒 Wajib tonton sampai selesai"
                "tr" -> "🔒 Tamamının izlenmesi zorunludur"
                "ur" -> "🔒 مکمل دیکھنا لازمی ہے"
                else -> "🔒 Non-Skippable (Full watch required)"
            }
            "wait_seconds_reward" -> when (l) {
                "bn" -> "পুরস্কার গ্রহণের জন্য %d সেকেন্ড অপেক্ষা করুন..."
                "es" -> "Espera %d segundos para reclamar la recompensa..."
                "hi" -> "पुरस्कार पाने के लिए %d सेकंड प्रतीक्षा करें..."
                "ar" -> "انتظر %d ثانية للحصول على المكافأة..."
                "fr" -> "Veuillez patienter %d secondes pour réclamer la récompense..."
                "de" -> "Bitte warte %d Sekunden auf deine Belohnung..."
                "zh" -> "请等待 %d 秒领取奖励..."
                "pt" -> "Aguarde %d segundos para resgatar a recompensa..."
                "ru" -> "Подождите %d секунд для получения награды..."
                "ja" -> "特典の受け取りまであと %d 秒お待ちください..."
                "ko" -> "보상을 받으려면 %d초 동안 기다려 주세요..."
                "id" -> "Harap tunggu %d detik untuk klaim hadiah..."
                "tr" -> "Ödülü almak için lütfen %d saniye bekleyin..."
                "ur" -> "انعام حاصل کرنے کے لیے %d سیکنڈ انتظار کریں..."
                else -> "Please wait %d seconds to claim reward..."
            }
            "ad_completed_congrats" -> when (l) {
                "bn" -> "🎉 অভিনন্দন! ভিডিও সম্পন্ন হয়েছে। আপনার পুরস্কার প্রস্তুত!"
                "es" -> "🎉 ¡Felicidades! Video completado. ¡Tu recompensa está lista!"
                "hi" -> "🎉 बधाई! वीडियो पूरा हुआ। आपका पुरस्कार तैयार है!"
                "ar" -> "🎉 تهانينا! اكتمل الفيديو. مكافأتك جاهزة!"
                "fr" -> "🎉 Félicitations ! Vidéo terminée. Votre récompense est prête !"
                "de" -> "🎉 Glückwunsch! Video beendet. Deine Belohnung ist bereit!"
                "zh" -> "🎉 恭喜！视频播放完毕。您的奖励已准备就绪！"
                "pt" -> "🎉 Parabéns! Vídeo concluído. Sua recompensa está pronta!"
                "ru" -> "🎉 Поздравляем! Видео завершено. Ваша награда готова!"
                "ja" -> "🎉 おめでとうございます！動画視聴が完了し、特典が解禁されました！"
                "ko" -> "🎉 축하합니다! 비디오 시청 완료. 보상이 준비되었습니다!"
                "id" -> "🎉 Selamat! Video selesai. Hadiah Anda siap!"
                "tr" -> "🎉 Tebrikler! Video tamamlandı. Ödülünüz hazır!"
                "ur" -> "🎉 مبارک ہو! ویڈیو مکمل ہو گئی۔ آپ کا انعام تیار ہے!"
                else -> "🎉 Congratulations! Video finished. Your reward is unlocked!"
            }
            "claim_reward_btn" -> when (l) {
                "bn" -> "পুরস্কার গ্রহণ ও আনলক করুন"
                "es" -> "Reclamar y Desbloquear"
                "hi" -> "पुरस्कार दावा करें और अनलॉक करें"
                "ar" -> "استلام المكافأة والفتح"
                "fr" -> "Réclamer la récompense et débloquer"
                "de" -> "Belohnung einlösen & freischalten"
                "zh" -> "领取奖励并解锁"
                "pt" -> "Resgatar Recompensa e Desbloquear"
                "ru" -> "Забрать награду и разблокировать"
                "ja" -> "特典を受け取って解除"
                "ko" -> "보상 받기 및 해제"
                "id" -> "Klaim Hadiah & Buka"
                "tr" -> "Ödülü Al ve Aç"
                "ur" -> "انعام حاصل کریں اور انلاک کریں"
                else -> "Claim Reward & Apply"
            }
            "playing_ad_status" -> when (l) {
                "bn" -> "ভিডিও চলছে (%ds)..."
                "es" -> "Reproduciendo (%ds)..."
                "hi" -> "विज्ञापन चल रहा है (%ds)..."
                "ar" -> "جاري العرض (%ds)..."
                "fr" -> "Lecture en cours (%ds)..."
                "de" -> "Wird abgespielt (%ds)..."
                "zh" -> "正在播放 (%ds)..."
                "pt" -> "Reproduzindo (%ds)..."
                "ru" -> "Воспроизведение (%ds)..."
                "ja" -> "再生中 (%ds)..."
                "ko" -> "재생 중 (%ds)..."
                "id" -> "Memutar (%ds)..."
                "tr" -> "Oynatılıyor (%ds)..."
                "ur" -> "চল رہا ہے (%ds)..."
                else -> "Playing Ad (%ds)..."
            }

            "after_streak" -> when (l) {
                "bn" -> "স্ট্রিকের পর"
                "es" -> "después de racha"
                "hi" -> "स्ट्रीक के बाद"
                "ar" -> "بعد السلسلة"
                "fr" -> "après la série"
                "de" -> "nach dem Streak"
                "zh" -> "连胜之后"
                "pt" -> "após a racha"
                "ru" -> "после серии"
                "ja" -> "ストリーク後"
                "ko" -> "스트릭 후"
                "id" -> "setelah streak"
                "tr" -> "seriden sonra"
                "ur" -> "سٹریک کے بعد"
                else -> "after streak"
            }
            "reason_prefix" -> when (l) {
                "bn" -> "কারণ"
                "es" -> "Razón"
                "hi" -> "कारण"
                "ar" -> "السبب"
                "fr" -> "Raison"
                "de" -> "Grund"
                "zh" -> "原因"
                "pt" -> "Razão"
                "ru" -> "Причина"
                "ja" -> "理由"
                "ko" -> "이유"
                "id" -> "Alasan"
                "tr" -> "Neden"
                "ur" -> "وجہ"
                else -> "Reason"
            }
            "notes_prefix" -> when (l) {
                "bn" -> "নোট"
                "es" -> "Nota"
                "hi" -> "नोट"
                "ar" -> "ملاحظة"
                "fr" -> "Note"
                "de" -> "Notiz"
                "zh" -> "备注"
                "pt" -> "Nota"
                "ru" -> "Заметка"
                "ja" -> "メモ"
                "ko" -> "노트"
                "id" -> "Catatan"
                "tr" -> "Not"
                "ur" -> "نوٹ"
                else -> "Note"
            }
            "no_description" -> when (l) {
                "bn" -> "কোনো বিবরণ নেই"
                "es" -> "Sin descripción"
                "hi" -> "कोई विवरण नहीं"
                "ar" -> "بدون وصف"
                "fr" -> "Pas de description"
                "de" -> "Keine Beschreibung"
                "zh" -> "无描述"
                "pt" -> "Sem descrição"
                "ru" -> "Нет описания"
                "ja" -> "説明なし"
                "ko" -> "설명 없음"
                "id" -> "Tidak ada deskripsi"
                "tr" -> "Açıklama yok"
                "ur" -> "کوئی تفصیل نہیں"
                else -> "No description"
            }

            else -> key
        }
    }

    fun getLocalizedHabitTitle(rawTitle: String?, lang: String): String {
        if (rawTitle.isNullOrBlank()) return get("default_habit_title", lang)
        val l = lang.lowercase()
        return when {
            rawTitle.contains("Smoking", ignoreCase = true) || rawTitle.contains("ধূমপান", ignoreCase = true) || rawTitle.contains("fumar", ignoreCase = true) -> when (l) {
                "bn" -> "ধূমপান ত্যাগ"
                "es" -> "Dejar de Fumar"
                "hi" -> "धूम्रपान छोड़ना"
                "ar" -> "الإقلاع عن التدخين"
                "fr" -> "Arrêter de fumer"
                "de" -> "Rauchen aufhören"
                "zh" -> "戒烟"
                "pt" -> "Parar de Fumar"
                "ru" -> "Бросить курить"
                "ja" -> "禁煙"
                "ko" -> "금연하기"
                "id" -> "Berhenti Merokok"
                "tr" -> "Sigarayı Bırakmak"
                "ur" -> "تمباکو نوشی چھوڑنا"
                else -> "Quit Smoking"
            }
            rawTitle.contains("Social Media", ignoreCase = true) || rawTitle.contains("সোশ্যাল মিডিয়া", ignoreCase = true) || rawTitle.contains("Redes Sociales", ignoreCase = true) -> when (l) {
                "bn" -> "সোশ্যাল মিডিয়া আসক্তি"
                "es" -> "Desintoxicación de Redes Sociales"
                "hi" -> "सोशल मीडिया से दूरी"
                "ar" -> "التخلص من إدمان وسائل التواصل"
                "fr" -> "Détox Réseaux Sociaux"
                "de" -> "Social Media Detox"
                "zh" -> "远离社交媒体"
                "pt" -> "Detox de Redes Sociais"
                "ru" -> "Детокс от соцсетей"
                "ja" -> "デジタルデトックス"
                "ko" -> "소셜 미디어 끊기"
                "id" -> "Detoks Media Sosial"
                "tr" -> "Sosyal Medya Detoksu"
                "ur" -> "سوشل میڈیا سے پاکی"
                else -> "Social Media Detox"
            }
            rawTitle.contains("Junk Food", ignoreCase = true) || rawTitle.contains("ফাস্ট ফুড", ignoreCase = true) || rawTitle.contains("Comida Chatarra", ignoreCase = true) -> when (l) {
                "bn" -> "ফাস্ট ফুড নিয়ন্ত্রণ"
                "es" -> "Control de Comida Chatarra"
                "hi" -> "जंक फूड नियंत्रण"
                "ar" -> "التحكم في الوجبات السريعة"
                "fr" -> "Contrôle Malbouffe"
                "de" -> "Junkfood-Kontrolle"
                "zh" -> "控制垃圾食品"
                "pt" -> "Controle de Junk Food"
                "ru" -> "Контроль фастфуда"
                "ja" -> "ジャンクフード制限"
                "ko" -> "정크푸드 줄이기"
                "id" -> "Kontrol Makanan Instan"
                "tr" -> "Abur Cubur Kontrolü"
                "ur" -> "جنک فوڈ پر کنٹرول"
                else -> "Junk Food Control"
            }
            rawTitle.contains("Gaming", ignoreCase = true) || rawTitle.contains("গেম", ignoreCase = true) || rawTitle.contains("Videojuegos", ignoreCase = true) -> when (l) {
                "bn" -> "গেম আসক্তি"
                "es" -> "Adicción a los Videojuegos"
                "hi" -> "गेमिंग की लत"
                "ar" -> "إدمان الألعاب الإلكترونية"
                "fr" -> "Addiction aux Jeux Vidéo"
                "de" -> "Gaming-Sucht"
                "zh" -> "克制网络游戏"
                "pt" -> "Vício em Jogos"
                "ru" -> "Игровая зависимость"
                "ja" -> "ゲーム依存の克服"
                "ko" -> "게임 중독 극복"
                "id" -> "Kecanduan Game"
                "tr" -> "Oyun Bağımlılığı"
                "ur" -> "گیمنگ کی عادت"
                else -> "Gaming Addiction"
            }
            rawTitle.contains("Sleep", ignoreCase = true) || rawTitle.contains("ঘুমানো", ignoreCase = true) || rawTitle.contains("Dormir", ignoreCase = true) -> when (l) {
                "bn" -> "দেরিতে ঘুমানো"
                "es" -> "Hábito de Dormir Tarde"
                "hi" -> "देर से सोने की आदत"
                "ar" -> "عادة النوم المتأخر"
                "fr" -> "Coucher tardif"
                "de" -> "Spätes Schlafengehen"
                "zh" -> "改善熬夜习惯"
                "pt" -> "Hábitos de Sono"
                "ru" -> "Привычка поздно спать"
                "ja" -> "夜更かし克服"
                "ko" -> "늦게 자는 습관"
                "id" -> "Tidur Larut Malam"
                "tr" -> "Geç Yatmak"
                "ur" -> "دیر سے سونے کی عادت"
                else -> "Late Sleep Habit"
            }
            rawTitle.contains("Caffeine", ignoreCase = true) || rawTitle.contains("কফি", ignoreCase = true) || rawTitle.contains("Cafeína", ignoreCase = true) -> when (l) {
                "bn" -> "অতিরিক্ত চা/কফি"
                "es" -> "Cafeína Excesiva"
                "hi" -> "अत्यधिक कैफीन"
                "ar" -> "الإفراط في الكافيين"
                "fr" -> "Excès de Caféine"
                "de" -> "Übermäßiges Koffein"
                "zh" -> "控制咖啡因"
                "pt" -> "Cafeína em Excesso"
                "ru" -> "Избыток кофеина"
                "ja" -> "カフェインの控え"
                "ko" -> "카페인 줄이기"
                "id" -> "Konsumsi Kafein"
                "tr" -> "Aşırı Kafein"
                "ur" -> "کافئین کا محدود استعمال"
                else -> "Excess Caffeine"
            }
            else -> rawTitle
        }
    }
}
